# Generated by Django 6.0.6 on 2026-07-03 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kittens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitten',
            name='photo',
            field=models.ImageField(default='default/Kitten_Default.png', upload_to='kittens/'),
        ),
        migrations.AlterField(
            model_name='kitten',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kittens', to='kittens.listing'),
        ),
    ]
