# Generated by Django 6.0.6 on 2026-07-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kittens', '0002_kitten_photo_alter_kitten_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitten',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AddField(
            model_name='kitten',
            name='spayed',
            field=models.BooleanField(default=False),
        ),
    ]
