# Generated by Django 6.0.6 on 2026-07-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kittens', '0003_kitten_gender_kitten_spayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitten',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
